### ISSUE TITLE
Not clear instructions

### ISSUE THREAD

**Issue by karam1ashqar** [facn5/CoffeeBros#50]
I don't get it, The search doesn't seem to work, and reviews are not being added

I feel like I'm lost, I don't want to say that it is not working application, but that's how it looks like in my browser.
we can't code review any broken sites or not finished codes.

I think you should act like the clients are stupid people who you should explain everything to them, and don't let them suffer by cloning and adding some sentences so it works, please make our life easier

**Comment by Bear-Coding** [comment]
Duplicated issue #40
